######################################################################
# Automatically generated by qmake (2.01a) gio feb 28 17:03:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywidget.h
SOURCES += main.cpp mywidget.cpp
